apiVersion: v1
kind: Service
metadata:
  name: nextcloud-service
spec:
  selector:
    app: nextcloud
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-ingress
spec:
  rules:
  - host: microk.local
    http:
      paths:
      - pathType: Prefix 
        path: "/"
        backend:
          service:
            name: nextcloud-service
            port:
              number: 80 